node {

  // job
  try {
    stage('build') {
      println('so far so good...')
    }
    stage('test') {
      println('A test has failed!')
      sh 'exit 1'
    }
  } catch(e) {
    // mark build as failed
    currentBuild.result = "FAILURE";

    // send opsgenie notification
    opsgenie(tags: "tag1,tag2" ,  teams: "ReleaseMangement",  priority: "P3")


    // throw the error
    throw e;
  }
}
